// Generated by CoffeeScript 1.3.3
(function() {

  module("Array compare");

  test("Comparing two empty arrays", function() {
    var a1, a2;
    a1 = [];
    a2 = [];
    return ok(a1.compare(a2), "Two empty arrays are equal");
  });

  test("Comparing two arrays that are not empty and are equal", function() {
    var a1, a2;
    a1 = [1, 12];
    a2 = [1, 12];
    return ok(a1.compare(a2), "Two not empty arrays are equal");
  });

  test("Comparing two arrays that are not empty and are not equal", function() {
    var a1, a2;
    a1 = [1, 2];
    a2 = [1, 12];
    return ok(!a1.compare(a2), "Two not empty arrays are not equal");
  });

  test("Array that is used for dictionary", function() {
    var a1, a2;
    a1 = [];
    a1["a"] = "1";
    a1["b"] = "2";
    a2 = [];
    a2["a"] = "1";
    a2["b"] = "2";
    ok(a1.compare(a2), "Two arrays are equeal");
    a1 = [];
    a1["1"] = "1";
    a1["2"] = "2";
    a2 = [];
    a2["1"] = "4";
    a2["2"] = "2";
    ok(!a1.compare(a2), "Two arrays are not equeal");
    a1 = [];
    a1["1"] = "1";
    a1["2"] = "2";
    a2 = [];
    a2["3"] = "1";
    a2["2"] = "2";
    ok(!a1.compare(a2), "Two arrays are not equeal");
    a1 = [];
    a1["1"] = "1";
    a1["2"] = "2";
    a2 = [];
    a2["3"] = "4";
    a2["2"] = "2";
    return ok(!a1.compare(a2), "Two arrays are not equeal");
  });

  test("Array enumerator", function() {
    var a, en;
    a = ['red', 'green', 'blue'];
    en = a.GetEnumerator();
    ok(en.MoveNext() === true, "First MoveNext succeeded");
    ok(en.Current() === 'red', "Current element is red");
    ok(en.MoveNext() === true, "Second MoveNext succeeded");
    ok(en.Current() === 'green', "Current element is red");
    ok(en.MoveNext() === true, "Third MoveNext succeeded");
    ok(en.Current() === 'blue', "Current element is red");
    ok(en.MoveNext() === false, "Fourth MoveNext is false");
    en.Reset();
    ok(en.MoveNext() === true, "First MoveNext succeeded");
    ok(en.Current() === 'red', "Current element is red");
    ok(en.MoveNext() === true, "Second MoveNext succeeded");
    ok(en.Current() === 'green', "Current element is red");
    ok(en.MoveNext() === true, "Third MoveNext succeeded");
    ok(en.Current() === 'blue', "Current element is red");
    return ok(en.MoveNext() === false, "Fourth MoveNext is false");
  });

}).call(this);
