// Generated by CoffeeScript 1.3.3
(function() {

  module("EdgeData");

  test("EdgeData compareTo test", function() {
    var iog = window.execom.iog;
    var e1, e2, e3, e4, e5, e6;
    e1 = new iog.EdgeData(iog.EdgeType.Property, "bb");
    e2 = new iog.EdgeData(iog.EdgeType.Property, "bb");
    ok(e1.compareTo(e2) === 0, "EdgeData objects are equals");
    e3 = new iog.EdgeData(iog.EdgeType.Property, "bc");
    ok(e1.compareTo(e3) < 0, "EdgeData object e1 is smaller");
    e4 = new iog.EdgeData(iog.EdgeType.Property, "ba");
    ok(e1.compareTo(e4) > 0, "EdgeData object e4 is bigger");
    e5 = new iog.EdgeData(iog.EdgeType.Contains, "bb");
    ok(e1.compareTo(e5) > 0, "EdgeData object e1 is bigger");
    e6 = new iog.EdgeData(iog.EdgeType.RootObject, "bb");
    return ok(e1.compareTo(e6) < 0, "EdgeData object e1 is smaller");
  });

}).call(this);
