// Generated by CoffeeScript 1.3.3
(function() {

  module("Object");

  test("Obejct equals test", function () {
    var iog = window.execom.iog;
    var a, b;
    a = {
      "a": 1,
      "b": 2,
      "c": 3
    };
    b = {
      "a": 1,
      "b": 2,
      "c": 3
    };
    ok(iog.equals(a, b) === true, "Objects are equal");
    a = {
      "a": 1,
      "d": 2,
      "c": 3
    };
    b = {
      "a": 1,
      "b": 2,
      "c": 3
    };
    ok(iog.equals(a, b) === false, "Objects are not equal");
    a = {
      "a": 1,
      "b": 3,
      "c": 3
    };
    b = {
      "a": 1,
      "b": 2,
      "c": 3
    };
    ok(iog.equals(a, b) === false, "Objects are not equal");
    a = {
      "a": 1,
      "d": 2,
      "c": 3
    };
    b = {
      "a": 1,
      "h": 2,
      "c": 3
    };
    return ok(iog.equals(a, b) === false, "Objects are not equal");
  });

}).call(this);
