// Generated by CoffeeScript 1.3.3
(function() {

  module("SortedList");

  test("Adding test", function() {
    var iog = window.execom.iog;
    var dict, len;
    dict = new iog.SortedList();
    dict.Add("1", "a");
    len = dict.Length();
    ok(len === 1, "Adding test");
    dict.Add("3", "b");
    dict.Add("2", "s");
    return ok(dict.array[1].key === "2", "Element is added in sorted way");
  });

  test("Removing test", function() {
    var iog = window.execom.iog;
    var dict;
    dict = new iog.SortedList();
    dict.Add("1", "a");
    dict.Add("3", "b");
    dict.Add("2", "s");
    dict.Remove("2");
    ok(dict.Contains("2") === false, "Element is removed");
    return ok(dict.Length() === 2, "SortedList size is 2");
  });

  test("Index of test", function() {
    var iog = window.execom.iog;
    var dict;
    dict = new iog.SortedList();
    dict.Add("1", "a");
    dict.Add("3", "b");
    dict.Add("2", "s");
    ok(dict.IndexOf("1") === 0, "First element found");
    ok(dict.IndexOf("2") === 1, "Second element found");
    ok(dict.IndexOf("3") === 2, "Third element found");
    return ok(dict.IndexOf("s") === -1, "Element is not found");
  });

}).call(this);
