// Generated by CoffeeScript 1.3.3
(function() {

  module("Table element");

  test("CompareTo Method", function() {
    var iog = window.execom.iog;
    var te1, te2, te3, te4;
    te1 = new iog.TableElement("s1", 1);
    te2 = new iog.TableElement("s3", 1);
    te3 = new iog.TableElement("s4", 2);
    te4 = new iog.TableElement("s5", 0);
    ok(te1.compareTo(te2) === 0, "Objects are same");
    ok(te1.compareTo(te3) < 0, "te1 object is smaller");
    return ok(te1.compareTo(te4) > 0, "te4 object is bigger");
  });

}).call(this);
